# Default configurations https://github.com/sasstools/sass-lint/blob/master/lib/config/sass-lint.yml
options:
    formatter: stylish
    merge-default-rules: true
files:
    include: 'src/scss/**/*.s+(a|c)ss'
rules:
    # Extends
    extends-before-mixins: 2
    extends-before-declarations: 2
    placeholder-in-extend: 1
    # Mixins
    mixins-before-declarations: 2
    # Line Spacing
    empty-line-between-blocks: 2
    single-line-per-selector: 2
    # Disallows
    property-units:
        - 1
        - global: ['em', 'px', 'ms']
    no-color-literals: 0
    no-color-keywords: 0
    no-duplicate-properties: 2
    no-vendor-prefixes: 2
    # Name Formats
    class-name-format:
        - 1
        - convention: hyphenatedbem
    variable-name-format:
        - 1
        - convention: hyphenatedbem
    # Style Guide
    bem-depth: 1
    border-zero: 2
    indentation:
        - 2
        - size: 4
    property-sort-order: 1
    # Inner Spacing
    space-after-comma: 2
    space-around-operator: 0

    #mixins-before-declarations
